### ISSUE TITLE
Templatize Azure DevOps Pipeline

### ISSUE THREAD

**Issue by Nighteyez07** [tferrari92/automate-all-the-things#2]
Within the Azure DevOps folder, there are a variety of steps which are repeated. Following the DRY principle where you can and leverage templates, you can find a lot of the reference material at https://learn.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops&pivots=templates-includes. Myself I tend to use Includes style templates vs excludes. The nice part is that an included template can start at almost all levels of a Pipeline. 
- Stages
- Jobs
- Steps
- Or even just specific steps

With templates you can reference variables that will exist in your Pipeline and you can also utilize Parameters which would work excellent in a scenario like your deployments where they are all almost the same but the difference is just the name of the environment. Maybe two parameters such as EnvFile for your variable file you are referencing and/or EnvironmentName such as _dev, test, or prod_

**Comment by Nighteyez07** [comment]
This whole block would be great to templatize, add a few parameters to set the stage name, variable file to use, and environment (or combine and use some variable/string substiution)

https://github.com/tferrari92/automate-all-the-things/blob/1493890ac35e4cf9c65ef27b63315e6159fee8c0/azure-devops/03-build-and-deploy-frontend.yml#L50C1-L103C37

**Comment by tferrari92** [comment]
Thank you! I didn't know about this feature. 

In order to keep this first version as simple and straightforward as possible, I will have this implemented from the Hardcore Edition onwards.

Thanks for the contribution 🙏!
